/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Sun Aug 25 17:33:01 EDT 2019 ----! */

#include <jni.h>
#include <stdlib.h>

#include <assert.h>


/*   Java->C glue code:
 *   Java package: io.sqlc.JSQLCOREPRONDKWrapper
 *    Java method: long jsql_pro_db_open(int jsql_pro_api_version, java.lang.String filename, int flags)
 *     C function: jsql_handle_t jsql_pro_db_open(int jsql_pro_api_version, const char *  filename, int flags);
 */
JNIEXPORT jlong JNICALL 
Java_io_sqlc_JSQLCOREPRONDKWrapper_jsql_1pro_1db_1open__ILjava_lang_String_2I(JNIEnv *env, jclass _unused, jint jsql_pro_api_version, jstring filename, jint flags) {
  const char* _strchars_filename = NULL;
  jsql_handle_t _res;
  if ( NULL != filename ) {
    _strchars_filename = (*env)->GetStringUTFChars(env, filename, (jboolean*)NULL);
  if ( NULL == _strchars_filename ) {
      (*env)->ThrowNew(env, (*env)->FindClass(env, "java/lang/OutOfMemoryError"),
                       "Failed to get UTF-8 chars for argument \"filename\" in native dispatcher for \"jsql_pro_db_open\"");
      return 0;
    }
  }
  _res = jsql_pro_db_open((int) jsql_pro_api_version, (char *) _strchars_filename, (int) flags);
  if ( NULL != filename ) {
    (*env)->ReleaseStringUTFChars(env, filename, _strchars_filename);
  }
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.sqlc.JSQLCOREPRONDKWrapper
 *    Java method: java.lang.String jsql_pro_execute(long dbHandle, java.lang.String batch_json, int ll)
 *     C function: const char *  jsql_pro_execute(jsql_handle_t dbHandle, const char *  batch_json, int ll);
 */
JNIEXPORT jstring JNICALL 
Java_io_sqlc_JSQLCOREPRONDKWrapper_jsql_1pro_1execute__JLjava_lang_String_2I(JNIEnv *env, jclass _unused, jlong dbHandle, jstring batch_json, jint ll) {
  const char* _strchars_batch_json = NULL;
  const char *  _res;
  if ( NULL != batch_json ) {
    _strchars_batch_json = (*env)->GetStringUTFChars(env, batch_json, (jboolean*)NULL);
  if ( NULL == _strchars_batch_json ) {
      (*env)->ThrowNew(env, (*env)->FindClass(env, "java/lang/OutOfMemoryError"),
                       "Failed to get UTF-8 chars for argument \"batch_json\" in native dispatcher for \"jsql_pro_execute\"");
      return 0;
    }
  }
  _res = jsql_pro_execute((jsql_handle_t) dbHandle, (char *) _strchars_batch_json, (int) ll);
  if ( NULL != batch_json ) {
    (*env)->ReleaseStringUTFChars(env, batch_json, _strchars_batch_json);
  }
  if (NULL == _res) return NULL;
  return (*env)->NewStringUTF(env, _res);
}


/*   Java->C glue code:
 *   Java package: io.sqlc.JSQLCOREPRONDKWrapper
 *    Java method: void jsql_pro_internal_cleanup(long dbHandle)
 *     C function: void jsql_pro_internal_cleanup(jsql_handle_t dbHandle);
 */
JNIEXPORT void JNICALL 
Java_io_sqlc_JSQLCOREPRONDKWrapper_jsql_1pro_1internal_1cleanup__J(JNIEnv *env, jclass _unused, jlong dbHandle) {
  jsql_pro_internal_cleanup((jsql_handle_t) dbHandle);
}


